"""
Gate-volume validation — what each market gate moves, model vs OMIE, at any horizon.

This is the measurement layer every market-chain extension is judged against.
It runs in two modes:

    python plotting/gate_volume_validation.py <results>            single run
    python plotting/gate_volume_validation.py <before> <after>     A/B comparison

The A/B mode is the one that validates a change: it reports the same metrics for
two runs side by side with the delta, so "did this extension do anything" has a
number rather than an impression.

What it measures
----------------
  1. NET position change per technology per gate, against the observed OMIE
     sessions.  The only quantity comparable between the model and the Spanish
     market, and therefore the calibration target.
  2. GROSS movement and the reshuffling index (gross ÷ net system change).
     Separates netting a forecast error from reshuffling the merit order.
  3. Cleared price level and intraday spread per gate, against observed.
  4. Generation-mix NRMSE against the OMIE cleared programme.
  5. Reservoir-hydro energy per day, against the mid-term schedule's budget.

Why gross volume is NOT the calibration target
----------------------------------------------
Hagemann & Weber (2015, pp. 18 and 24) show observed Iberian intraday volume
exceeds the fundamental ("competitive") benchmark by a factor of six, because
Spanish rules route a firm's rescheduling between its OWN plants through the
intraday exchange.  This model has no firms, so that component of real volume
has no counterpart here.  Koks et al. (2026, p. 8) confirm PowerVision's Active
case IS that competitive benchmark.  Matching gross volume to OMIE would fit a
number generated by a mechanism the model does not contain.  Report gross as a
diagnostic; calibrate on net.

Scalability
-----------
The chain currently runs two days but is intended for a sampled multi-week
horizon, so nothing here may assume the two 2024 study days:

  * **Dates are discovered from the results**, never hardcoded.  Reference data
    is joined only for those days that have it (currently the two 2024 days),
    and model-side metrics are reported for every day found.
  * **The dispatch CSVs are streamed, not loaded.**  A gate carries ~2 340 unit
    rows per hour — 112 k rows for two days, but ~20 M rows and ~880 MB per
    gate over a full year, times five gates.  `pd.read_csv` on whole files does
    not survive that.  Each file is read in chunks and aggregated to
    (date, hour, category) on the way in, which collapses a year to ~96 k rows
    per gate regardless of fleet size.  This is why `load_chain` from
    `paper_figures_2024` is deliberately NOT reused — only its category
    vocabulary and its pure metric functions are.
  * **Per-day tables collapse to summaries** past a handful of days; the full
    per-day detail always goes to CSV.

Known comparison caveats, deliberately not papered over
-------------------------------------------------------
* The reference file's rows do NOT sum to zero: the `*_tot` columns leave a
  residual of -204, -364, -69 and -6 MW across the four day/session
  combinations.  A matched market should net out, so either a category is
  missing or the `Load` row's sign convention differs from the generation rows.
  **Confirm the file's provenance against OMIE's published reports before any
  number here becomes load-bearing.**
* The model has no IDA1, but Spain has run IDA1/IDA2/IDA3 since 14 June 2024,
  so the model's DA→ID2 step absorbs what the real market split over two
  sessions.  The ID3 comparison is the cleaner one.
* ID3 trades only delivery hours 12–23; both sides average over 24 hours with
  zeros elsewhere, so the means stay comparable.
* Gate deltas apply the XB import clipping from `_categorise`.  Reading the
  dispatch CSVs raw instead makes the border exchange look like fresh
  rescheduling — that error inflated DA→ID2 movement from 1.19 % to 5.68 % of
  demand on the 2035 runs.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from paper_figures_2024 import (  # noqa: E402
    CATEGORIES,
    DAY_LABEL,
    FIG_DIR,
    GATE_LABEL,
    MODEL_CAT,
    RESULTS,
    nrmse_by_category,
    weighted_nrmse,
)
from reference_data import load_reference  # noqa: E402

GATES = ["da", "id2", "id3", "cid", "bal"]

# MODEL_CAT keyed by a single joined string, so the (fuel, technology) lookup
# can be done with a vectorised Series.map rather than per row in Python.
FLAT_CAT = {f"{fuel}\x00{tech}": cat for (fuel, tech), cat in MODEL_CAT.items()}

# Rows per chunk when streaming a dispatch CSV.  500k rows of six narrow
# columns is a few tens of MB — small enough to be invisible, large enough that
# the per-chunk groupby overhead stays negligible.
CHUNK_ROWS = 500_000

# Past this many days the per-day tables stop being readable, so the console
# switches to across-day summaries.  The CSVs always carry full detail.
MAX_DAYS_SHOWN = 4

# Model category → the `tec` row of OMIE_intraday.csv.  "Renewable" aggregates
# the three variable-renewable categories the model carries separately.
TEC_OF_CATEGORY = {
    "Nuclear": "Nuclear",
    "Coal": "Coal",
    "Combined cycle": "Combined Cycle",
    "Hydro": "Hydro",
    "Pumped storage": "Pumped Storage",
    "Wind": "Renewable",
    "Solar PV": "Renewable",
    "Solar thermal": "Renewable",
    "Imports": "Inernational Interchange",   # sic — the file's own spelling
    # "Cogeneration & waste" has no clean counterpart: OMIE books it partly
    # under "Other", which is 0.0 on both study days.  Left unmapped and
    # reported separately rather than forced into a row.
}

# Which gates are compared against the reference is taken from the reference
# itself (see `reference_data`), not hardcoded — a longer horizon that adds an
# IDA1 series is picked up without an edit here.

# Technologies whose energy is checked against the mid-term reservoir budget.
RESERVOIR_TECHS = {("Hydro", "reservoir")}


# ── Streaming loader ─────────────────────────────────────────────────────────
def _category_frame(path: Path) -> pd.DataFrame | None:
    """Stream one <gate>_dispatch.csv into (date, hour) × category MW.

    Aggregates inside the read loop so peak memory is one chunk, not one file.
    Applies the same XB import clipping as `paper_figures_2024._categorise`:
    the XB_* units carry net border exchange on a signed variable, and OMIE's
    reference stack is domestic generation plus GROSS imports, so only the
    positive part belongs in the comparison.
    """
    if not path.exists() or path.stat().st_size == 0:
        return None
    parts = []
    reader = pd.read_csv(
        path,
        usecols=["date", "hour", "fuel", "technology", "dispatch_mw"],
        dtype={"date": "string", "hour": "int16", "fuel": "string",
               "technology": "string", "dispatch_mw": "float32"},
        chunksize=CHUNK_ROWS,
    )
    for chunk in reader:
        # Vectorised (fuel, technology) -> category.  Looking the tuple up per
        # row in Python costs one interpreter round-trip per row, which is ~20M
        # of them per gate over a year; joining the two columns and using
        # Series.map keeps the lookup inside pandas and turns a multi-minute
        # pass into a short one.
        key = chunk["fuel"].astype(str) + "\x00" + chunk["technology"].astype(str)
        chunk = chunk.assign(category=key.map(FLAT_CAT))
        chunk = chunk[chunk["category"].notna()]
        if chunk.empty:
            continue
        xb = chunk["category"] == "Imports"
        if xb.any():
            chunk.loc[xb, "dispatch_mw"] = chunk.loc[xb, "dispatch_mw"].clip(lower=0.0)
        parts.append(chunk.groupby(["date", "hour", "category"], observed=True)
                          ["dispatch_mw"].sum())
    if not parts:
        return None
    total = pd.concat(parts).groupby(level=[0, 1, 2]).sum()
    return total.unstack("category").fillna(0.0).sort_index()


def _tech_energy(path: Path, techs=RESERVOIR_TECHS) -> pd.Series | None:
    """Daily energy [MWh] of specific (fuel, technology) pairs, streamed.

    Kept separate from the category aggregation because the category vocabulary
    lumps reservoir hydro together with run-of-river, and the reservoir budget
    question is specifically about the reservoir units.
    """
    if not path.exists() or path.stat().st_size == 0:
        return None
    parts = []
    reader = pd.read_csv(
        path,
        usecols=["date", "hour", "fuel", "technology", "dispatch_mw"],
        dtype={"date": "string", "fuel": "string", "technology": "string",
               "dispatch_mw": "float32"},
        chunksize=CHUNK_ROWS,
    )
    flat = {f"{f}\x00{t}" for f, t in techs}
    for chunk in reader:
        key = chunk["fuel"].astype(str) + "\x00" + chunk["technology"].astype(str)
        chunk = chunk[key.isin(flat)]
        if chunk.empty:
            continue
        parts.append(chunk.groupby("date", observed=True)["dispatch_mw"].sum())
    if not parts:
        return None
    return pd.concat(parts).groupby(level=0).sum()


def load_run(results) -> dict:
    """Everything the metrics below need from one run, aggregated on the way in."""
    results = Path(results)
    run = {"path": results, "gates": {}, "profiles": {}}
    for g in GATES:
        frame = _category_frame(results / f"{g}_dispatch.csv")
        if frame is not None:
            run["gates"][g] = frame
        prof = results / f"{g}_profiles.csv"
        if prof.exists() and prof.stat().st_size > 0:
            run["profiles"][g] = pd.read_csv(prof)
    mp = results / "market_prices.csv"
    run["market_prices"] = pd.read_csv(mp) if mp.exists() and mp.stat().st_size else None
    run["reservoir_mwh"] = _tech_energy(results / "bal_dispatch.csv")
    run["days"] = sorted({d for f in run["gates"].values()
                          for d in f.index.get_level_values("date").unique()})
    return run


def _mix(run, gate, date) -> pd.DataFrame:
    """Hourly MW per category for one gate and day → [hour × category]."""
    f = run["gates"][gate]
    d = f[f.index.get_level_values("date") == date]
    d = d.droplevel("date").reindex(range(24)).fillna(0.0)
    return d.reindex(columns=[c for c in CATEGORIES if c in d.columns], fill_value=0.0)


def gate_movement(run, date) -> dict:
    """Signed MW change per category at each gate, versus its predecessor."""
    seq = [g for g in GATES if g in run["gates"]]
    return {GATE_LABEL[b]: _mix(run, b, date) - _mix(run, a, date)
            for a, b in zip(seq, seq[1:])}


# ── Metrics ──────────────────────────────────────────────────────────────────
def _split(delta: pd.Series) -> tuple[float, float, float, float]:
    """(neg, pos, net, gross) means over the hours of one category's delta.

    Matches the OMIE file's construction: negative and positive parts are taken
    hour by hour and only then averaged, so a technology that moves up in one
    hour and down the next shows movement on both legs rather than cancelling.
    """
    v = delta.reindex(range(24)).fillna(0.0).to_numpy(dtype=float)
    neg = float(np.mean(np.clip(v, None, 0.0)))
    pos = float(np.mean(np.clip(v, 0.0, None)))
    return neg, pos, neg + pos, pos - neg


def model_load_row(run) -> pd.DataFrame:
    """The model's own demand revision per gate, as a "Load" row [MW].

    The model has no demand-side traders: the load forecast changes between
    gates and generation absorbs it.  But that revision is the fundamental
    driver of every intraday trade, so putting it beside OMIE's `Load` row
    answers what the generation rows cannot — whether the model's forecast
    updates are the right SIZE.  If the model revises demand by far less than
    the market retraded, under-trading in the generation rows follows
    arithmetically and is not a behavioural finding.

    Sign convention is "change in demand", load(gate) − load(prev).  OMIE's own
    convention for its `Load` row is a buy/sell position change and has NOT been
    confirmed to match; treat as indicative.
    """
    seq = [g for g in GATES if g in run["profiles"]]
    rows = []
    for date in run["days"]:
        for a, b in zip(seq, seq[1:]):
            pa, pb = run["profiles"][a], run["profiles"][b]
            la = pa.loc[pa["date"] == date].set_index("hour")["load_mw"]
            lb = pb.loc[pb["date"] == date].set_index("hour")["load_mw"]
            if la.empty or lb.empty:
                continue
            neg, pos, net, gross = _split(lb - la)
            rows.append({"date": date, "gate": GATE_LABEL[b], "tec": "Load",
                         "model_neg_mw": neg, "model_pos_mw": pos,
                         "model_net_mw": net, "model_gross_mw": gross})
    return pd.DataFrame(rows)


def model_gate_table(run) -> pd.DataFrame:
    rows = []
    for date in run["days"]:
        for gate, piv in gate_movement(run, date).items():
            for cat in piv.columns:
                neg, pos, net, gross = _split(piv[cat])
                if gross == 0.0:
                    continue
                rows.append({"date": date, "gate": gate, "category": cat,
                             "model_neg_mw": neg, "model_pos_mw": pos,
                             "model_net_mw": net, "model_gross_mw": gross})
    return pd.DataFrame(rows)


def reference_gate_table(ref, days) -> pd.DataFrame:
    """Reference session volumes as neg/pos/net/gross, for the days it covers.

    `reference_data` has already normalised whichever on-disk format is in use,
    so this only has to restrict to the run's days and derive net and gross.
    """
    cols = ["date", "gate", "tec", "ref_neg_mw", "ref_pos_mw",
            "ref_net_mw", "ref_gross_mw"]
    raw = ref.get("intraday")
    if raw is None or raw.empty:
        return pd.DataFrame(columns=cols)
    out = raw[raw["date"].isin(set(days))].copy()
    if out.empty:
        return pd.DataFrame(columns=cols)
    out["ref_net_mw"] = out["ref_neg_mw"] + out["ref_pos_mw"]
    out["ref_gross_mw"] = out["ref_pos_mw"] - out["ref_neg_mw"]
    return out[cols]


def reference_gates(ref) -> set:
    """Gate labels the reference carries volumes for (ID2, ID3, ... )."""
    raw = ref.get("intraday")
    if raw is None or raw.empty:
        return set()
    return set(raw["gate"].unique())


def compare_to_omie(run, ref) -> pd.DataFrame:
    """Model vs OMIE net position change, aggregated to OMIE's vocabulary."""
    mod = model_gate_table(run)
    if mod.empty:
        return mod
    gates = reference_gates(ref)
    if gates:
        mod = mod[mod["gate"].isin(gates)].copy()
    mod["tec"] = mod["category"].map(TEC_OF_CATEGORY)
    unmapped = sorted(mod.loc[mod["tec"].isna(), "category"].unique())
    if unmapped:
        print(f"  note: no OMIE counterpart, excluded from this table: {', '.join(unmapped)}")
    agg = (mod.dropna(subset=["tec"])
              .groupby(["date", "gate", "tec"], as_index=False)
              [["model_neg_mw", "model_pos_mw", "model_net_mw", "model_gross_mw"]].sum())
    load = model_load_row(run)
    if not load.empty:
        if gates:
            load = load[load["gate"].isin(gates)]
        agg = pd.concat([agg, load], ignore_index=True)
    out = agg.merge(reference_gate_table(ref, run["days"]),
                    on=["date", "gate", "tec"], how="outer").fillna(0.0)
    out["net_err_mw"] = out["model_net_mw"] - out["ref_net_mw"]
    out["gross_ratio"] = np.where(out["ref_gross_mw"].abs() > 1e-9,
                                  out["model_gross_mw"] / out["ref_gross_mw"], np.nan)
    return out.sort_values(["date", "gate", "tec"]).reset_index(drop=True)


def reshuffling_index(run) -> pd.DataFrame:
    """System-level gross movement vs net system change, per day and gate.

        ratio ≈ 1   the gate moved what the forecast update required
        ratio ≫ 1   the gate reshuffled the merit order on top of that

    A high ratio is the signature this project is chasing — but it is also what
    a degenerate LP produces, so read it together with a degeneracy check before
    attributing it to behaviour.  PowerVision adds a random 0–1e-3 NOK/MWh
    perturbation to every marginal cost for exactly this reason (Koks et al.
    2026, p. 8); this chain relies instead on the lexicographic
    minimum-movement pass in `da.jl:327`, which only breaks ties within
    `cost_tol`.
    """
    rows = []
    for date in run["days"]:
        for gate, piv in gate_movement(run, date).items():
            v = piv.reindex(range(24)).fillna(0.0).to_numpy(dtype=float)
            gross = float(np.abs(v).sum(axis=1).mean())
            net_system = float(np.abs(v.sum(axis=1)).mean())
            rows.append({"date": date, "gate": gate, "gross_mw": gross,
                         "net_system_mw": net_system,
                         "reshuffle_ratio": np.nan if net_system < 1e-9
                         else gross / net_system})
    return pd.DataFrame(rows)


def demand_share(run) -> pd.DataFrame:
    """Gross movement as a share of that day's BAL demand, per gate [%].

    The unit the 2035 report quotes (9.7 % of demand), kept for continuity.
    """
    prof = run["profiles"].get("bal")
    if prof is None:
        return pd.DataFrame(columns=["date", "gate", "gross_pct_of_demand"])
    rows = []
    for date in run["days"]:
        load = prof.loc[prof["date"] == date, "load_mw"].to_numpy(dtype=float)
        if load.size == 0 or load.sum() == 0:
            continue
        for gate, piv in gate_movement(run, date).items():
            v = piv.reindex(range(24)).fillna(0.0).to_numpy(dtype=float)
            rows.append({"date": date, "gate": gate,
                         "gross_pct_of_demand": 100.0 * float(np.abs(v).sum()) / load.sum()})
    return pd.DataFrame(rows)


def price_table(run, ref) -> pd.DataFrame:
    """Modelled price per gate against observed [EUR/MWh], with the spread.

    `spread_eur_mwh` is max−min over the day.  It matters as much as the level:
    a flat price is a day on which no storage asset can earn anything.
    """
    mp = run.get("market_prices")
    rows = []
    for date in run["days"]:
        obs = ref["price"].get(date)
        if obs is not None:
            rows.append({"date": date, "stage": "OMIE observed",
                         "mean_eur_mwh": float(obs.mean()),
                         "min_eur_mwh": float(obs.min()),
                         "max_eur_mwh": float(obs.max()),
                         "spread_eur_mwh": float(obs.max() - obs.min())})
        if mp is None:
            continue
        d = mp[mp["date"] == date]
        for stage in ("DA", "ID2", "ID3", "CID", "BAL"):
            s = d.loc[d["stage"] == stage, "price_eur_mwh"].to_numpy(dtype=float)
            if s.size:
                rows.append({"date": date, "stage": stage,
                             "mean_eur_mwh": float(s.mean()),
                             "min_eur_mwh": float(s.min()),
                             "max_eur_mwh": float(s.max()),
                             "spread_eur_mwh": float(s.max() - s.min())})
    return pd.DataFrame(rows)


def mix_error(run, ref) -> pd.DataFrame:
    """Generation-mix NRMSE against the OMIE cleared programme, per day and gate.

    Only for days OMIE reference data exists for; a longer horizon simply
    reports fewer rows here while every other metric still covers every day.
    """
    rows = []
    for date in run["days"]:
        obs = ref["omie"].get(date)
        if obs is None:
            continue
        for gate in run["gates"]:
            err = nrmse_by_category(_mix(run, gate, date), obs)
            rows.append({"date": date, "gate": GATE_LABEL[gate],
                         "weighted_nrmse": weighted_nrmse(err)})
    return pd.DataFrame(rows)


def reservoir_energy(run) -> pd.DataFrame:
    """Reservoir-hydro energy per day [GWh], the quantity the budget caps.

    The mid-term schedule's release becomes a daily cap in every market gate
    (`[bellman].hydro_budget`), and the chain prints it as "reservoir budget:
    X GWh/day".  If the cap binds, a hydro BID markup cannot change how much
    hydro energy runs — only when it runs and what sets the price.  That
    distinction decides whether R2 addresses the December validation error, so
    it is measured rather than assumed.
    """
    s = run.get("reservoir_mwh")
    if s is None:
        return pd.DataFrame(columns=["date", "reservoir_gwh"])
    return (s.rename("reservoir_gwh").div(1000.0).reset_index()
             .rename(columns={"index": "date"}))


# ── Reporting ────────────────────────────────────────────────────────────────
def _show(title, df, fmt="%.2f"):
    print(f"\n{title}\n{'-' * len(title)}")
    if df is None or df.empty:
        print("  (no rows)")
        return
    with pd.option_context("display.width", 200, "display.max_columns", 30,
                           "display.float_format", lambda v: fmt % v):
        print(df.to_string(index=False))


def _label_days(df):
    if df.empty or "date" not in df:
        return df
    return df.assign(day=df["date"].map(lambda d: DAY_LABEL.get(d, d)))


def metrics(run, ref) -> dict:
    return {"omie": compare_to_omie(run, ref),
            "reshuffling": reshuffling_index(run),
            "demand_share": demand_share(run),
            "prices": price_table(run, ref),
            "mix": mix_error(run, ref),
            "reservoir": reservoir_energy(run)}


def report_single(run, ref, out_dir: Path):
    m = metrics(run, ref)
    days = run["days"]
    many = len(days) > MAX_DAYS_SHOWN

    if many:
        print(f"\n{len(days)} days found — console shows across-day means; "
              f"per-day detail is in the CSVs.")
        _show("Net position change vs OMIE (mean MW, averaged over days with reference)",
              m["omie"].groupby(["gate", "tec"], as_index=False).mean(numeric_only=True))
    else:
        for date in days:
            _show(f"Net position change by technology — {DAY_LABEL.get(date, date)} "
                  f"(mean MW; model vs OMIE session)",
                  m["omie"][m["omie"]["date"] == date].drop(columns=["date"]), "%.1f")

    rsh = m["reshuffling"]
    _show("Reshuffling index — gross movement vs net system change (mean MW)",
          rsh.groupby("gate", as_index=False).mean(numeric_only=True) if many
          else _label_days(rsh).drop(columns=["date"]))
    dsh = m["demand_share"]
    _show("Gross movement as a share of BAL demand [%]",
          dsh.groupby("gate", as_index=False).mean(numeric_only=True) if many
          else _label_days(dsh).drop(columns=["date"]))
    _show("Generation-mix weighted NRMSE vs OMIE cleared programme",
          m["mix"].groupby("gate", as_index=False).mean(numeric_only=True) if many
          else _label_days(m["mix"]).drop(columns=["date"]), "%.3f")
    _show("Reservoir hydro energy [GWh/day] — compare against the "
          "'reservoir budget' the run printed",
          _label_days(m["reservoir"]).drop(columns=["date"]) if not many
          else m["reservoir"].describe().T)
    _show("Cleared price by gate vs observed [EUR/MWh]",
          m["prices"].groupby("stage", as_index=False).mean(numeric_only=True) if many
          else _label_days(m["prices"]).drop(columns=["date"]))

    out_dir.mkdir(parents=True, exist_ok=True)
    for name, df in m.items():
        df.to_csv(out_dir / f"gate_{name}.csv", index=False)
    print(f"\nWrote gate_*.csv ({', '.join(sorted(m))}) to {out_dir}")
    return m


def report_ab(run_a, run_b, ref, out_dir: Path):
    """Same metrics for two runs, side by side, with the delta.

    This is what says whether an extension changed anything.  Metrics are
    averaged across whatever days both runs share, so it works equally on two
    study days and on a sampled year.
    """
    ma, mb = metrics(run_a, ref), metrics(run_b, ref)
    shared = sorted(set(run_a["days"]) & set(run_b["days"]))
    print(f"\nA = {run_a['path']}\nB = {run_b['path']}\n"
          f"{len(shared)} day(s) in common: {', '.join(shared)}")

    def delta(key, index, value_cols):
        a = ma[key][ma[key]["date"].isin(shared)] if "date" in ma[key] else ma[key]
        b = mb[key][mb[key]["date"].isin(shared)] if "date" in mb[key] else mb[key]
        if a.empty or b.empty:
            return pd.DataFrame()
        a = a.groupby(index, as_index=False)[value_cols].mean()
        b = b.groupby(index, as_index=False)[value_cols].mean()
        out = a.merge(b, on=index, suffixes=("_A", "_B"))
        for c in value_cols:
            out[f"{c}_delta"] = out[f"{c}_B"] - out[f"{c}_A"]
        return out.sort_values(index)

    _show("Reshuffling index — A vs B",
          delta("reshuffling", ["gate"], ["gross_mw", "net_system_mw", "reshuffle_ratio"]))
    _show("Gross movement as % of demand — A vs B",
          delta("demand_share", ["gate"], ["gross_pct_of_demand"]))
    _show("Price level and spread — A vs B",
          delta("prices", ["stage"], ["mean_eur_mwh", "spread_eur_mwh"]))
    _show("Generation-mix weighted NRMSE — A vs B",
          delta("mix", ["gate"], ["weighted_nrmse"]), "%.3f")
    _show("Net position change vs OMIE — A vs B",
          delta("omie", ["gate", "tec"], ["model_net_mw", "model_gross_mw"]), "%.1f")

    out_dir.mkdir(parents=True, exist_ok=True)
    for key, index, cols in (
        ("reshuffling", ["gate"], ["gross_mw", "net_system_mw", "reshuffle_ratio"]),
        ("demand_share", ["gate"], ["gross_pct_of_demand"]),
        ("prices", ["stage"], ["mean_eur_mwh", "spread_eur_mwh"]),
        ("mix", ["gate"], ["weighted_nrmse"]),
        ("omie", ["gate", "tec"], ["model_net_mw", "model_gross_mw"]),
    ):
        delta(key, index, cols).to_csv(out_dir / f"ab_{key}.csv", index=False)
    print(f"\nWrote ab_*.csv to {out_dir}")


def main(argv):
    out_dir = Path(FIG_DIR)
    ref = load_reference()
    if len(argv) >= 2:
        a, b = load_run(argv[0]), load_run(argv[1])
        for r in (a, b):
            if not r["gates"]:
                raise SystemExit(f"No *_dispatch.csv in {r['path']}")
        report_ab(a, b, ref, out_dir)
        return
    run = load_run(argv[0] if argv else RESULTS)
    if not run["gates"]:
        raise SystemExit(f"No *_dispatch.csv in {run['path']} — run the chain first.")
    print(f"Reading model results from : {run['path']}")
    print(f"Gates found                : {', '.join(sorted(run['gates']))}")
    print(f"Days found                 : {len(run['days'])}")
    report_single(run, ref, out_dir)


if __name__ == "__main__":
    main(sys.argv[1:])
